version: "3.8"

services:
    zookeeper:
      image: confluentinc/cp-zookeeper:7.5.0
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
      ports:
        - "2181:2181"

    kafka:
      image: "confluentinc/cp-kafka:7.5.0"
      depends_on:
        - zookeeper
      ports:
        - "9092:9092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKERPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://KAFKA:9092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTIR: 1

    redis:
      image: redis:7.2
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data

    postgres:
      image: postgres:15
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: sentry
        POSTGRES_PASSWORD: sentrypass
        POSTGRES_DB: sentry_db
      volumes:
        - pg_data:/var/lib/postgresql/data

    sentry:
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
        - kafka
        - redis
        - postgres
      ports:
        - "8080:8080"
      environment:
        KAFKA_ADDR: kafka:9092
        REDIS_ADDR: redis:6379
        POSTGRES_DSN: postgres://sentry:sentrypass@postgres:5432/sentry_db?sslmode=disable
      command: ["/sentry"]


volumes:
  pd_data:
  redis_data:  