server:
  host: "0.0.0.0"
  port: 8080

kafka:
  brokers:
    - "kafka:9092"
  event_topic: "events_topic"
  consumer_group_id: "sentry-core"

redis:
  addr: "kafka:6379"
  db: 0

postgres:
  dsn: "postgres://sentry:sentrypass@postgres:5432/sentry_db?sslmode=disable"

log:
  level: "info"
